version: '3.0'

volumes:
  etc_pihole:
  etc_dnsmasq.d:
  etc_unbound.conf.d:

services:
  pihole:
    container_name: synology_pihole
    image: keithdw/pihole:latest
    build:
      context: ./pihole
      dockerfile: Dockerfile.pihole
    hostname: syn_pihole
    mac_address: d0:ca:ab:cd:ef:01
    cap_add: # Uncomment if you want to use Pi-Hole for DHCP
      - NET_ADMIN
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
      - 22/tcp
    environment:
      - FTLCONF_LOCAL_IPV4=192.168.170.253
      - TZ=Europe/London
      - WEBPASSWORD=
      - PIHOLE_DNS_=192.168.170.254
    #  - PIHOLE_DNS_=192.168.170.1
      - PIHOLE_DOCKER_TAG=2022.11.2    
      - WEBTHEME=default-auto
      - REV_SERVER=fale
      #- REV_SERVER_TARGET=${REV_SERVER_TARGET}
      #- REV_SERVER_DOMAIN=${REV_SERVER_DOMAIN}
      #- REV_SERVER_CIDR=${REV_SERVER_CIDR}
      - DNS_BOGUS_PRIV=true
      - DNS_FQDN_REQUIRED=true
      #- DHCP_ACTIVE=${DHCP_ACTIVE}
      #- DHCP_START=${DHCP_START}
      #- DHCP_END=${DHCP_END}
      #- DHCP_ROUTER=${DHCP_ROUTER}
      #- DHCP_LEASETIME=${DHCP_LEASETIME}
      - DNSSEC=true
      - DNSMASQ_LISTENING=local
    volumes:
      - etc_pihole:/etc/pihole:rw
      - etc_dnsmasq.d:/etc/dnsmasq.d:rw
    networks:
      pihole-unbound:
        ipv4_address: 192.168.170.253
    restart: always
  
  unbound: 
    container_name: synology_unbound
    image: keithdw/unbound:latest
    build: 
      context: ./unbound
      dockerfile: Dockerfile.unbound
    hostname: syn-unbound
    mac_address: d0:ca:ab:cd:ef:02
    volumes:
      - etc_unbound.conf.d:/etc/unbound.conf.d:rw

    ports:
      - 53/tcp
      - 53/udp
    networks:
      pihole-unbound:
        ipv4_address: 192.168.170.254
      pihole-bridge:
    restart: always

networks:
  pihole-unbound:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.170.0/24
          gateway: 192.168.170.1
          ip_range: 192.168.170.253/30 # 192.168.170.253 and 192.168.170.254
  pihole-bridge:
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1
          ip_range: 192.168.10.2/32 # 192.168.170.253 and 192.168.170.254