ARG PIHOLE_VERSION
FROM pihole/pihole:${PIHOLE_VERSION:-latest}
RUN apt update && apt full-upgrade -y && install unbound -y

COPY lighttpd-external.conf /etc/lighttpd/external.conf 
COPY 99-edns.conf /etc/dnsmasq.d/99-edns.conf
COPY 50-dhcp-extra.conf /etc/dnsmasq.d/50-dhcp-extra.conf
COPY 04-pihole-static-dhcp.conf /etc/dnsmasq.d/04-pihole-static-dhcp.conf
COPY unbound-pihole.conf /etc/unbound/unbound.conf.d/pi-hole.conf

ENTRYPOINT ./s6-init